name: hockeyR-data-update

on:
  schedule:
      - cron: '0 8 * * *'

jobs:
  hockeyR-data-update:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Update hockeyR data repo
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
        run: Rscript update_hockeyR_data.R
      - name: Commit and update repo
        run: |
          git config --global user.name "hockeyR-data-github-actions[bot]"
          git config --global user.email "hockeyR-data-github-actions@users.noreply.github.com"
          git commit -a -m "Updated play-by-play data"
          git push origin
